import React, { useState } from "react";
import Link from "next/link";

export default function Home() {
  const sessionTypes = [
    { id: "pattern-break", title: "The Pattern", hook: "Why Do I Keep Choosing This?", description: "You've had the same fight with 3 different people.", duration: "20 min", price: "$7", emoji: "🔄" },
    { id: "after-fight", title: "After the Fight", hook: "What Was That Actually About?", description: "The fight wasn't really about what you thought.", duration: "20 min", price: "$7", emoji: "💔" },
    { id: "breakup", title: "Breakup Breakdown", hook: "Processing What Actually Happened", description: "Breakups hurt. Understanding helps.", duration: "20 min", price: "$7", emoji: "💔" },
    { id: "group", title: "Group Session", hook: "You're Not Alone in This", description: "Your friends have the same patterns.", duration: "30 min", price: "$8", emoji: "👥" },
  ];

  return (
    <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
      <nav className="border-b border-slate-700"><div className="max-w-6xl mx-auto px-6 py-4"><h1 className="text-3xl font-black text-white">🔀 It's Complicated</h1><div className="text-sm text-slate-300">It's complicated. Let's talk about it.'t have to be.</div></div></nav>
      <section className="max-w-6xl mx-auto px-6 py-20 text-center"><h2 className="text-6xl font-black text-white mb-6">Why do you keep choosing the same person?</h2><p className="text-xl text-slate-300 mb-10">It's Complicated unravels what's actually happening. In 20 minutes, you'll understand patterns you've been repeating for years.</p><Link href="/session/pattern-break"><button className="bg-purple-600 hover:bg-purple-700 text-white px-8 py-3 rounded-lg font-bold">Start a Session →</button></Link></section>
      <section className="bg-slate-800/30 border-y border-slate-700 py-12"><div className="max-w-6xl mx-auto px-6"><div className="grid md:grid-cols-3 gap-8"><div className="text-center"><p className="text-slate-300 italic">"I just realized I'm the toxic one"</p><p className="text-slate-500 text-sm">— Sarah, 24</p></div><div className="text-center"><p className="text-slate-300 italic">"Why do I keep choosing emotionally unavailable people?"</p><p className="text-slate-500 text-sm">— James, 26</p></div><div className="text-center"><p className="text-slate-300 italic">"That made more sense than 2 years of therapy"</p><p className="text-slate-500 text-sm">— Alex, 28</p></div></div></div></section>
      <section className="max-w-6xl mx-auto px-6 py-16"><h3 className="text-4xl font-black text-white mb-12 text-center">What's on your mind?</h3><div className="grid md:grid-cols-2 gap-6">{sessionTypes.map(s => (<Link key={s.id} href={`/session/${s.id}`}><div className="bg-slate-800 border border-slate-700 rounded-xl p-6 hover:border-purple-500 cursor-pointer"><div className="flex justify-between mb-4"><div><div className="text-sm text-purple-400 font-bold mb-1 uppercase">{s.hook}</div><h3 className="text-2xl font-black text-white">{s.title}</h3></div><div className="text-3xl">{s.emoji}</div></div><p className="text-slate-300 mb-6">{s.description}</p><div className="flex justify-between pt-4 border-t border-slate-700"><span className="text-slate-400">{s.duration}</span><span className="text-purple-400 font-bold">{s.price}</span></div></div></Link>))}</div></section>
      <section className="bg-slate-800/50 border-t border-slate-700 py-16"><div className="max-w-6xl mx-auto px-6"><h3 className="text-4xl font-black text-white mb-12 text-center">Why It's Complicated Works</h3><div className="grid md:grid-cols-3 gap-8"><div className="bg-slate-700/30 rounded-lg p-6"><h4 className="font-black text-white mb-3">💭 Real Talk</h4><p className="text-slate-400">You understand exactly why you keep repeating these patterns.</p></div><div className="bg-slate-700/30 rounded-lg p-6"><h4 className="font-black text-white mb-3">⏱️ 20 minutes Changes Everything</h4><p className="text-slate-400">No fluff. Real breakthroughs.</p></div><div className="bg-slate-700/30 rounded-lg p-6"><h4 className="font-black text-white mb-3">🔒 Completely Private</h4><p className="text-slate-400">What you share stays with you.</p></div></div></div></section>
      <section className="max-w-4xl mx-auto px-6 py-16 text-center"><h3 className="text-4xl font-black text-white mb-4">Ready to actually talk about it??</h3><p className="text-xl text-slate-300 mb-8">It's complicated. But talking about it helps.</p><Link href="/session/pattern-break"><button className="bg-purple-600 hover:bg-purple-700 text-white px-10 py-4 rounded-lg font-bold text-lg">Start Your Session</button></Link></section>
      <footer className="border-t border-slate-700 text-center py-8 text-slate-500 text-sm"><p>It's Complicated — Understand your patterns. Transform your relationships.</p></footer>
    </div>
  );
}
